const ButtonStyles = {
    primaryButton: {
        width: "268px",
        height: "40px",
        backgroundColor: "#8338EC",
        borderRadius: "5px",
        padding: "10px 20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        color: "#FFFFFF",
        border: "none",
        cursor: "pointer",
        transition: "background-color 0.3s",
        fontFamily: "'FiraGO', sans-serif",
        fontWeight: 400,
        fontSize: "16px",
        lineHeight: "100%",
      },
    secondaryButton: {
        width: "225px",
        height: "39px",
        border: "1px solid #8338EC",
        borderRadius: "5px",
        backgroundColor: "#FFFFFF",
        color: "#000000",
        padding: "10px 20px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "10px",
        cursor: "pointer",
        transition: "border-color 0.3s",
        fontFamily: "'FiraGO', sans-serif",
        fontWeight: 400,
        fontSize: "16px",
        lineHeight: "100%",
    },
    tertiaryButton: {
        width: "155px",
        height: "35px",
        padding: "8px 20px",
        borderRadius: "20px",
        backgroundColor: "#8338EC",
        color: "#FFFFFF",
        border: "none",
        cursor: "pointer",
        transition: "background-color 0.3s",
        fontFamily: "'FiraGO', sans-serif",
        fontWeight: 400,
        fontSize: "16px",
        },
};

export default ButtonStyles;